version: 3

server: https://app.fossa.com

project:
  id: github.com/subhradip-bose/openfga-go-sdk
  name: github.com/subhradip-bose/openfga-go-sdk
  link: openfga.dev
  url: github.com/subhradip-bose/openfga-go-sdk
